// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNPos.Infrastructure.Data;

#nullable disable

namespace VNPos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VNPos.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VNPos.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("VNPos.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Product 1",
                            Price = 10000m,
                            QuantityInStock = 15
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Product 2",
                            Price = 20000m,
                            QuantityInStock = 25
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Product 3",
                            Price = 30000m,
                            QuantityInStock = 35
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Product 4",
                            Price = 40000m,
                            QuantityInStock = 45
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Product 5",
                            Price = 50000m,
                            QuantityInStock = 55
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Product 6",
                            Price = 60000m,
                            QuantityInStock = 65
                        },
                        new
                        {
                            ProductId = 7,
                            Name = "Product 7",
                            Price = 70000m,
                            QuantityInStock = 75
                        },
                        new
                        {
                            ProductId = 8,
                            Name = "Product 8",
                            Price = 80000m,
                            QuantityInStock = 85
                        },
                        new
                        {
                            ProductId = 9,
                            Name = "Product 9",
                            Price = 90000m,
                            QuantityInStock = 95
                        },
                        new
                        {
                            ProductId = 10,
                            Name = "Product 10",
                            Price = 100000m,
                            QuantityInStock = 105
                        },
                        new
                        {
                            ProductId = 11,
                            Name = "Product 11",
                            Price = 110000m,
                            QuantityInStock = 115
                        },
                        new
                        {
                            ProductId = 12,
                            Name = "Product 12",
                            Price = 120000m,
                            QuantityInStock = 125
                        },
                        new
                        {
                            ProductId = 13,
                            Name = "Product 13",
                            Price = 130000m,
                            QuantityInStock = 135
                        },
                        new
                        {
                            ProductId = 14,
                            Name = "Product 14",
                            Price = 140000m,
                            QuantityInStock = 145
                        },
                        new
                        {
                            ProductId = 15,
                            Name = "Product 15",
                            Price = 150000m,
                            QuantityInStock = 155
                        },
                        new
                        {
                            ProductId = 16,
                            Name = "Product 16",
                            Price = 160000m,
                            QuantityInStock = 165
                        },
                        new
                        {
                            ProductId = 17,
                            Name = "Product 17",
                            Price = 170000m,
                            QuantityInStock = 175
                        },
                        new
                        {
                            ProductId = 18,
                            Name = "Product 18",
                            Price = 180000m,
                            QuantityInStock = 185
                        },
                        new
                        {
                            ProductId = 19,
                            Name = "Product 19",
                            Price = 190000m,
                            QuantityInStock = 195
                        },
                        new
                        {
                            ProductId = 20,
                            Name = "Product 20",
                            Price = 200000m,
                            QuantityInStock = 205
                        });
                });

            modelBuilder.Entity("VNPos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            FullName = "",
                            PasswordHash = "$2a$12$hHllIk.YSLfs/t3fKnvXDeXqBdN.ZEyi1ecZwW6YLBnDj0ik3qR3q",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            FullName = "",
                            PasswordHash = "$2a$12$bih8ZVbkjDlewki73o5CnecyJAMCp5k0mBVaR3gWwbCt1MkGkLs.K",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("VNPos.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("VNPos.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VNPos.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VNPos.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
